# Generated by Django 5.2.2 on 2025-06-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailyupdate',
            options={'ordering': ['-received_at']},
        ),
        migrations.AlterField(
            model_name='dailyupdate',
            name='received_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='dailyupdate',
            name='source',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='dailyupdate',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='dailyupdate',
            unique_together={('title', 'received_at')},
        ),
    ]
