# Generated by Django 5.2.2 on 2025-06-11 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_dailyupdate_original_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('free', '자유게시판'), ('report', '신고게시판')], max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('male', '남성'), ('female', '여성'), ('other', '기타')], max_length=10)),
                ('age', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
